### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by yangdaowu** [dc3ea9f/vico_challenge_baseline#20]
extract coefficients for videos error
python face_recon_videos.py \
  --input_dir ../../data/listening_head/videos/ \
  --keypoint_dir ../../data/listening_head/keypoints/ \
  --output_dir ../../data/listening_head/recons/ \
  --inference_batch_size 128 \
  --name=face_recon_feat0.2_augment \
  --epoch=20 \
  --model facerecon

loading the model from ./checkpoints/face_recon_feat0.2_augment/epoch_20.pth
  0%|          | 0/880 [00:00<?, ?it/s]create glctx on device cuda:0
 60%|██████    | 530/880 [10:34<06:58,  1.20s/it]
Traceback (most recent call last):
  File "/home/yangdw/PycharmProjects/VICO2023/vico_challenge_baseline/Deep3DFaceRecon_pytorch/face_recon_videos.py", line 158, in <module>
    main(opt, model)
  File "/home/yangdw/PycharmProjects/VICO2023/vico_challenge_baseline/Deep3DFaceRecon_pytorch/face_recon_videos.py", line 115, in main
    model.test()
  File "/home/yangdw/PycharmProjects/VICO2023/vico_challenge_baseline/Deep3DFaceRecon_pytorch/models/base_model.py", line 162, in test
    self.forward()
  File "/home/yangdw/PycharmProjects/VICO2023/vico_challenge_baseline/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 137, in forward
    self.facemodel.compute_for_render(output_coeff)
  File "/home/yangdw/PycharmProjects/VICO2023/vico_challenge_baseline/Deep3DFaceRecon_pytorch/models/bfm.py", line 284, in compute_for_render
    face_shape = self.compute_shape(coef_dict['id'], coef_dict['exp'])
  File "/home/yangdw/PycharmProjects/VICO2023/vico_challenge_baseline/Deep3DFaceRecon_pytorch/models/bfm.py", line 99, in compute_shape
    return face_shape.reshape([batch_size, -1, 3])
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 3] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by dc3ea9f** [comment]
It seems caused by the `output_coeff` being wrong calculated. Please check whether the `output_coeff` is normal or not after this [line](https://github.com/dc3ea9f/vico_challenge_baseline/blob/3793a4a35812ab1d4e31301fe78919953eebd662/Deep3DFaceRecon_pytorch/models/facerecon_model.py#LL134C17-L134C17).

If you still encounter any problems, please send an email to [me](mailto:mhzhou99@outook.com) with your contact (e.g. WeChat ID).

**Comment by yangdaowu** [comment]
I download the data set again and start the trial again. Thanks!

**Comment by dc3ea9f** [comment]
Good job!
